### ISSUE TITLE
remove auth

### ISSUE THREAD

**Issue by Ostedtinkerer** [MMRIZE/MMM-CalDAV#10]
Hello,
Is it possible to remove Auth from .ics url?

**Comment by eouia** [comment]
No. That is the main feature of this module. If you want a public opened ics URL, just get it from your CalDAV provider. 
(Or, can you explain why you need it?)

**Comment by Ostedtinkerer** [comment]
I need to get a .ics url without authentication. The app that should read it, does not support authentication.
I use Synology dsm, with there Calender. And that does not provide a .ics url, but instead caldav url.

The .ics url should be used in magicmirror app, and "Homepage" app as a dashboard with calender, but it does not provide auth, and compatible with caldav.
So then i thougt this module could be used without auth.

**Comment by eouia** [comment]
For security reasons, I made the hosted ics file that needed authorization. MagicMirror is very weak for that kind of security issue. However, I'll consider updating the module to work without auth. (But I cannot promise I'll do it sooner.)

**Comment by Ostedtinkerer** [comment]
This would be used just for local use.

Thanks for your response, and this module. Fingers crossed for the update.

**Comment by eouia** [comment]
I decided I'd not remove the auth process. Because this module is not the ICAL deliverer. I think you'd better to find other module or program for that purpose. Sorry.
