### ISSUE TITLE
Birthdays form ICloud

### ISSUE THREAD

**Issue by Superpjeter** [MMRIZE/MMM-CalDAV#3]
I don't get the Birthdays  from the iCloud server, should this be possible?

**Comment by eouia** [comment]
That kind is not calendar; it is `contact`. So that is `CardDAV`, not `CalDAV`. This module doesn't implement CardDAV. So, it is not supported.
(However, I think it would be interesting. When I have some enough time, I'll implement it.)

**Comment by Superpjeter** [comment]
Would be nice, I am looking forward to it.

**Comment by eouia** [comment]
Updated #4
