### ISSUE TITLE
Repeating entries in a calendar

### ISSUE THREAD

**Issue by tulpenwase** [MMRIZE/MMM-CalDAV#6]
Hello MMRIZE,

Thank you very much for this module. Thanks to your instructions it works great but unfortunately not all calendar entries are displayed for me. There are recurring entries in my calendar. These are entries that were created months or years ago and are repeated every week. These entries are currently not displayed in my Magic Mirror. Unfortunately, I have not found out why this is the case. Have I overlooked something in the configuration or can such entries not be displayed?

i see forward

**Comment by eouia** [comment]
I think probably this issue, not mine.
https://forum.magicmirror.builders/topic/18388/default-calendar-module-not-showing-some-recurring-events?_=1705582517291
However, could you send me the target ics file (in your `service` folder)? (eouia0819@gmail.com)

**Comment by tulpenwase** [comment]
Thank you for your reply. I was able to solve the problem myself. It seems that some of my entries were incorrect. These are probably still corpses from a database crash a long time ago. I didn't notice them before because they were displayed on the mobile phone. After I removed these entries and created new ones, everything is displayed as usual. 
Thank you for your help and you can close the ticket.
